### ISSUE TITLE
Layout issues in landscape (iPad). And alpha slider still shows when disabled.

### ISSUE THREAD

**Issue by iCrazeiOS** [SparkDev97/libSparkColourPicker#2]
Screenshots Attached Of The First Issue.

Second Issue: I am using `<key>alpha</key>
				<false/>`, but the alpha slider is still appearing in the preferences.
![IMG_0016](https://user-images.githubusercontent.com/39101269/72550605-0264ee00-388b-11ea-8e6e-a90e3c2396f0.PNG)
![IMG_0018](https://user-images.githubusercontent.com/39101269/72550606-02fd8480-388b-11ea-8590-075b310b2dcf.PNG)

**Comment by SparkDev97** [comment]
Second issue is fixed in repo version.

Will fix the landscape issues in the next version.

**Comment by iCrazeiOS** [comment]
Perfect thanks

On 4 Feb 2020, at 22:40, Spark <notifications@github.com> wrote:

﻿

Second issue is fixed in repo version.

Will fix the landscape issues in the next version.
