### ISSUE TITLE
SparkColourPickerCell not showing correctly unless a different tweak is installed

### ISSUE THREAD

**Issue by CobreDev** [SparkDev97/libSparkColourPicker#3]
I'm working on integrating libSparkColourPicker into my tweak, but I can only get the SparkColourPickerCell to show if I have another tweak that depends on libSparkColourPicker installed. For example: If I install my tweak (ZenithDark), and make sure libSparkColourPicker is installed, the cell where the color picker should be shows up looking like a cell that is used for multi-page prefs (See first attached screenshot). However, when I install a tweak that utilizes libSparkColourPicker, it works fine (See second screenshot). I can't figure out why this is happening!

I've double checked that it's not another tweak messing with it, so I'm not sure what to do now. 

Thanks!

![IMG_914F87A71F4C-1](https://user-images.githubusercontent.com/36574329/73792455-566c3f80-4772-11ea-82e2-bda82775fef8.jpeg)

![IMG_0410](https://user-images.githubusercontent.com/36574329/73792476-65eb8880-4772-11ea-874b-94204db9fbaa.PNG)

**Comment by SparkDev97** [comment]
This would happen if your preference bundle is not loading the library (and the other tweak is loading it for you).
Make sure you have included "..._LIBRARIES = sparkcolourpicker" in your Makefile for your preference bundle, not just for your tweak.

**Comment by CobreDev** [comment]
Yeah, I have that in both makefiles

**Comment by SparkDev97** [comment]
Well the library is not getting loaded for some reason...

You could try dlopen it from your preference bundle, but I'm not sure why it would be necessary.

**Comment by CobreDev** [comment]
So I guess I didn't realize I needed to `#import "SparkColourPickerUtils.h"` in my RootListController. That seems to have fixed it!
