### ISSUE TITLE
Color reverting back to fallback

### ISSUE THREAD

**Issue by CobreDev** [SparkDev97/libSparkColourPicker#4]
I'm trying to make a switch that controls whether or not my tweak should use a custom color, and my code looks something like this:

`-(void)setBackgroundColor:(UIColor *)backgroundColor {

    NSString* colourString = NULL;
    NSDictionary* preferencesDictionary = [NSDictionary dictionaryWithContentsOfFile: @"/var/mobile/Library/Preferences/com.mac-user669.zenithdark.plist"];
    if(preferencesDictionary)
    {
        colourString = [preferencesDictionary objectForKey: @"aColorOfMine"];
    }
    UIColor* selectedColour = [SparkColourPickerUtils colourWithString: colourString withFallback: @"#FF00FF"];
    if (@available(iOS 13, *)) {
    if (self.traitCollection.userInterfaceStyle == UIUserInterfaceStyleDark) {
       if (kCustomDarkColorEnabled) {

       %orig(selectedColour); 
    }
    else {
       %orig([UIColor blueColor]);
    }
    }

    else {
    %orig;
    }
  }
}`

Everything works fine until I turn off kCustomDarkColorEnabled and respring, and then the color goes back to the fallback color. What am I doing wrong?

Thanks!

Edit: To clarify, the SparkColourPicker's color gets totally removed from the preference file

**Comment by SparkDev97** [comment]
Sounds like your preferences controller is clearing/overwriting the plist file.
It should be making a copy of the plist, editing whatever has been changed, and writing it back. Not just taking the preferences set and writing a totally new dictionary.

I recommend looking at KarenPrefs for an example of how to do this properly
https://github.com/angelXwind/KarenPrefs/blob/master/KarenPrefsListController.m

Relevant code is:
```

-(void) setPreferenceValue:(id)value specifier:(PSSpecifier *)specifier {
	if ([self karenPrefsShouldBypassCfprefsd]) {
		NSMutableDictionary *karenPrefsPlist = [[NSMutableDictionary alloc] initWithContentsOfFile:[NSString stringWithFormat:@"/User/Library/Preferences/%@.plist", [specifier.properties objectForKey:@"defaults"]]];
		[karenPrefsPlist setObject:value forKey:[specifier.properties objectForKey:@"key"]];
		[karenPrefsPlist writeToFile:[NSString stringWithFormat:@"/User/Library/Preferences/%@.plist", [specifier.properties objectForKey:@"defaults"]] atomically:1];
		if ([specifier.properties objectForKey:@"PostNotification"]) {
			CFNotificationCenterPostNotification(CFNotificationCenterGetDarwinNotifyCenter(), (CFStringRef)[specifier.properties objectForKey:@"PostNotification"], NULL, NULL, YES);
		}
	}
	[super setPreferenceValue:value specifier:specifier];
}
```
